dist: trusty
sudo: false

language: node_js
node_js:
  - "node"
cache: yarn

script:
  - yarn build

before_deploy:
  - touch ./build/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $CI_USER_TOKEN
  local-dir: build
